name: Deploy Frontend Nuxt to aaPanel

on:
  push:
    branches:
      - main  # Trigger ketika ada push ke branch 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Install dependencies
    - name: Install dependencies
      uses: oven-sh/setup-bun@v2
    - run: cd frontend && bun install

    # Step 3: Build project
    - run: cd frontend && bun run generate

    # Step 4: Upload build hasil ke aaPanel menggunakan FTP
    - name: Deploy to aaPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}     # FTP Server
        username: ${{ secrets.FTP_USERNAME_FE }} # FTP username
        password: ${{ secrets.FTP_PASSWORD_FE }} # FTP password
        local-dir: ./frontend/dist/                  # Direktori local project yang akan di-upload
        server-dir: / # Direktori di server tempat Anda mengupload
        protocol: ftp                         # Bisa ftp, ftps, sftp
        exclude: |
          **/storage
          **/bootstrap/cache
          **/vendor/**
          **/.git*
          **/.git*/**
          **/node_modules/**

